// import 'swiper/css';
// import "swiper/css/navigation";
// import "swiper/css/pagination";
import "/public/assets/css/bootstrap.min.css";
import "/public/assets/css/all.min.css";
import "/public/assets/css/animate.css";
import "/public/assets/css/magnific-popup.css";
import "/public/assets/css/meanmenu.css";
import "/public/assets/css/swiper-bundle.min.css";
import "/public/assets/css/nice-select.css";
import "/public/assets/css/main.css";
// import "/public/favicon.png";
import "../styles/globals.css";

import { Kumbh_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Link from "next/link";

const kumbh = Kumbh_Sans({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "NewGen",
  // description: "Generated by create next app",
  icons: {
    // icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kumbh.className}`}>
        {/* <Toaster position="top-right"/> */}
        <Link href="https://lordicon.com/"></Link>
        {children}
      </body>
    </html>
  );
}
